version: '3'

services:
  timetable-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    labels:
      caddy: timetable.wmtech.cc
      caddy.reverse_proxy: "{{upstreams 8000}}"
    environment:
      - PYTHONUNBUFFERED=1 